//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Flowly
{
    /// <summary>
    /// This is an emurations containg the direction a component can face
    /// Left or right. It is used to better display the value of the direction
    /// </summary>
    public enum Direction : int
    {
        Left,
        Right,
    }
}