//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
/// <summary>
/// Objects of this class will be the "drawing" place of the user. A grid will contain components in it.
/// </summary>
public class Grid
{
	private List<ComponentDrawn> listOfComponents;

	private Graphics graphic;

	private int id;

	private string name;

	public virtual IEnumerable<ComponentDrawn> ComponentDrawn
	{
		get;
		set;
	}
    
    /// <summary>
    /// Adds a component to the listOfComponents list.
    /// </summary>
    /// <param name="givenComponent"></param>
    /// <returns>True if successfull, false otherwise</returns>
	public virtual bool AddComponentDrawnToGridList(ComponentDrawn givenComponent)
	{
		throw new System.NotImplementedException();
	}
    /// <summary>
    /// Opposite of the other method.
    /// </summary>
    /// <param name="givenComponent"></param>
    /// <returns>True if successfull, false otherwise.</returns>
	public virtual bool RemoveComponentDrawnFromGridList(ComponentDrawn givenComponent)
	{
		throw new System.NotImplementedException();
	}

}

