//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Flowly
{
    /// <summary>
    /// This is an interface that enables an object to be edited
    /// </summary>
    public interface IEditable
    {
        /// <summary>
        /// This method is used to edit an object
        /// </summary>
        void Edit();

    }
}
