//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;
namespace Flowly
{
    /// <summary>
    /// Sub class of the "ComponentDrawn" class. A particular component called - Merger. Nothing specific in it. Set diffCurrFlowPossible 
    /// needs to be false.
    /// </summary>
    public class Merger : ComponentDrawn
    {
        public Merger(Point theUpperLeftCorner, Point theBottomRightCorner, Direction theDirection, Image theImageSource,
            bool theDiffCurrFlowPossible, float theCapacity, float theCurrentFlow) : base( theUpperLeftCorner,  theBottomRightCorner,  theDirection,  theImageSource,
             theDiffCurrFlowPossible,  theCapacity,  theCurrentFlow)
        {

        }

        public override bool CreateConnectionPoints()
        {
            ConnectionPoint connPoint1 = new ConnectionPoint(currentFlow/2,coordinatesUpperLeftCorner,)
        }
    }
}

