//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Flowly
{
    /// <summary>
    /// Enumeration that contains the type of propertie that can be set, if it is possible you can adjust the flow that can pass.
    /// If the component is an adjustable splitter it has the property of Adjustable.
    /// Properties: FLOW and Adjustable
    /// </summary>
    public enum PropertiesEnum : int
    {
        Flow,
        Adjustable,
    }
}