//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Drawing;
namespace Flowly
{
    [Serializable]
    /// <summary>
    /// Sub class of the "ComponentDrawn" class. A particular component called - Sink. Nothing specific in it. Set diffCurrFlowPossible 
    /// needs to be false.
    /// </summary>
    public class Sink : ComponentDrawn
    {
        public Sink(Rectangle theRectangle) : base(theRectangle)
        {
            imageResource = Image.FromFile("images\\sink2.png");
            diffCurrFlowPossible = false;
            CreateConnectionPoints();
            this.EditableProperties.Add(GeneratedCode.EditablePropertiesEnum.capacity);
        }

        //overloading

        public Sink(Rectangle theRectangle,float theCapacity) : base(theRectangle)
        {
            imageResource = Image.FromFile("images\\sink2.png");
            diffCurrFlowPossible = false;
            CreateConnectionPoints();
            this.EditableProperties.Add(GeneratedCode.EditablePropertiesEnum.capacity);

            SetCapacity(theCapacity);
        }

        public override bool CreateConnectionPoints()
        {
            try
            {
                ConnectionPoint conn1 = new ConnectionPoint(rectangleBig, this, false, new Point(rectangleBig.X+22,rectangleBig.Y+5));
                listOfConnectionPoints.Add(conn1);
                return true;
            }
            catch
            {
                return false;
            }
        }

       
    }

}