//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;
/// <summary>
/// Not a "ComponentDrawn"! This is a Component from the Toolbox! Can be just used to CREATE an instance of "ComponentDrawn"!
/// </summary>
public class ToolboxComponent
{
	private int id;

	private string name;

	private Image image;

}

