//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AdjMerger : Merger
{
	public virtual float topExitFlow
	{
		get;
		set;
	}

	public virtual float bottomExitFlow
	{
		get;
		set;
	}

}

