//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ComponentDrawn
{
	private List<ConnectionPoint> listOfConnectionPoints;

	private Point coordinates;

	private List<Properties> listOfProperties;

	private Direction direction;

	private Image imageSource;

	private Point coordinates1;

	private List<ComponentDrawn> listOfComponentDrawn;

	private bool diffCurrFlowPossible;

	private float capacity;

	public virtual IEnumerable<ConnectionPoint> ConnectionPoint
	{
		get;
		set;
	}

}

