//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConnectionPoint
{
	private Point coordinates;

	private Float currentFlow;

	private bool isOutput;

	private ComponentDrawn componentDrawnBelong;

	private bool isAvailable;

	private Point coordinates1;

	public virtual bool SetAvailable(bool givenAvailable)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool SetCurrentFlow(Float givenFlow)
	{
		throw new System.NotImplementedException();
	}

}

