//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConnectionPoint
{
	public virtual Coordinates coordinates
	{
		get;
		set;
	}

	public virtual float flow
	{
		get;
		set;
	}

	public virtual bool isOutput
	{
		get;
		set;
	}

	public virtual Component component
	{
		get;
		set;
	}

	public virtual Component Component
	{
		get;
		set;
	}

}

