//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FlowComponent
{
	public virtual List<ConnectionPoint> listOfConnectionPoints
	{
		get;
		set;
	}

	public virtual Coordinates coordinates
	{
		get;
		set;
	}

	public virtual List<Properties> listOfProperties
	{
		get;
		set;
	}

	public virtual Direction direction
	{
		get;
		set;
	}

}

