//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Grid
{
	private List<ComponentDrawn> listOfComponents;

	private Graphics graphic;

	private int id;

	private string name;

	public virtual IEnumerable<ComponentDrawn> ComponentDrawn
	{
		get;
		set;
	}

	public virtual void AddComponentDrawnToGridList(ComponentDrawn givenComponent)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveComponentDrawnFromGridList(ComponentDrawn givenComponent)
	{
		throw new System.NotImplementedException();
	}

}

