//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Pipe : ConnectionComponent
{
	public virtual ConnectionPoint connection1
	{
		get;
		set;
	}

	public virtual ConnectionPoint connection2
	{
		get;
		set;
	}

	public virtual IEnumerable<ConnectionPoint> ConnectionPoint
	{
		get;
		set;
	}

}

