//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SystemFlowly
{
	public virtual List<Component> listOfToolboxItems
	{
		get;
		set;
	}

	public virtual Grid grid
	{
		get;
		set;
	}

}

