//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SystemFlowly
{
	private List<ToolboxComponent> listOfToolboxItems;

	private Grid grid;

	private List<Change> changes;

	public virtual Grid Grid
	{
		get;
		set;
	}

	public virtual IEnumerable<DialogWindow> DialogWindow
	{
		get;
		set;
	}

	public virtual IEnumerable<ToolboxComponent> ToolboxComponent
	{
		get;
		set;
	}

	public virtual IEnumerable<Change> Change
	{
		get;
		set;
	}

	public virtual bool CheckFreeSpot(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool MakeSpotFree(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool MakeSpotBusy(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateComponentDrawn(string cName, ConnectionPoint cTop, ConnectionPoint cBottom, int cCapacity)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool RemoveComponent(ComponentDrawn givenComponent)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool EditComponentDrawn(ComponentDrawn givenComponent)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool ClearGrid(Grid givenGrid)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool SaveGrid(Grid givenGrid)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool NewFile()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool OpenFile()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool UndoLastChange()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool CreateChange(Change givenChange)
	{
		throw new System.NotImplementedException();
	}

	private bool AddCompDrawnToList(object ComponentDrawn component)
	{
		throw new System.NotImplementedException();
	}

	private bool RemoveComponentDrawnFromList(object ComponentDrawn component)
	{
		throw new System.NotImplementedException();
	}

}

