//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SystemFlowly
{
	private List<ToolboxComponent> listOfToolboxItems;

	private Grid grid;

	private List<Change> changes;

	public virtual Grid Grid
	{
		get;
		set;
	}

	public virtual DialogWindow DialogWindow
	{
		get;
		set;
	}

	public virtual IEnumerable<ToolboxComponent> ToolboxComponent
	{
		get;
		set;
	}

	public virtual IEnumerable<Change> Change
	{
		get;
		set;
	}

	public virtual bool CheckFreeSpot(object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool MakeSpotFree(object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool MakeSpotBusy(object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateComponentDrawn(object string name, object Point top, object Point bottom, object int capacity)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool RemoveComponent(object ComponentDrawn theComponent)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool EditComponentDrawn(object ComponentDrawn theComponent)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool ClearGrid(object Grid theGrid)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool SaveGrid(object Grid theGrid)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool NewFile()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool OpenFile()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool UndoLastChange()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool CreateChange(object Change theChange)
	{
		throw new System.NotImplementedException();
	}

}

